name: polyglot_flutter_sdk
description: flutter sdk for Polyglot, a localize app api
version: 0.0.1
author: Anderson <anderson.cancado@gaspardbruno.com>
#homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  shared_preferences: ^2.0.3
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter